### ISSUE TITLE
Scout API for Drone communication?

### ISSUE THREAD

**Issue by nyameaama** [AltitudeAngel/Scout#1]

**Comment by nyameaama** [comment]
For the development of drone flight computers, is a Scout API available

**Comment by rupertbenbrook** [comment]
The current version of the Scout firmware uses Altitude Angel's Surveillance API, which is documented [here](https://docs.altitudeangel.com/docs/surveillance-api). At the moment this code isn't separated as a library from the Scout firmware, but that's something that would be interesting to do. Does that answer your question?

**Comment by nyameaama** [comment]
Yes thank you
